(function(){
var G=window.IOE_GRADE||6;
var DATA2={
e1:['Unit 1 · At my birthday party',[['pizza','bánh pizza'],['pasta','mì Ý'],['popcorn','bỏng ngô'],['party','bữa tiệc']],'The pizza is yummy.'],
e2:['Unit 2 · In the backyard',[['kite','diều'],['bike','xe đạp'],['kitten','mèo con'],['backyard','sân sau']],'She is flying a kite.'],
e3:['Unit 3 · At the seaside',[['sea','biển'],['sand','cát'],['sail','cánh buồm'],['sun','mặt trời']],'I can see the sea.'],
e4:['Unit 4 · In the countryside',[['river','sông'],['road','con đường'],['rabbit','con thỏ'],['rainbow','cầu vồng']],'I can see a river.'],
e5:['Unit 5 · In the classroom',[['book','quyển sách'],['desk','bàn học'],['pen','bút'],['classroom','lớp học']],'The book is on the desk.'],
e6:['Unit 6 · On the farm',[['cow','con bò'],['hen','gà mái'],['goat','con dê'],['farm','nông trại']],'I can see a cow.'],
e7:['Unit 7 · In the kitchen',[['cup','cốc'],['cake','bánh'],['cook','nấu ăn'],['kitchen','nhà bếp']],'The cup is in the kitchen.'],
e8:['Unit 8 · In the village',[['village','làng'],['house','ngôi nhà'],['field','cánh đồng'],['road','con đường']],'This is my village.'],
e9:['Unit 9 · In the grocery store',[['rice','gạo'],['milk','sữa'],['bag','túi'],['shop','cửa hàng']],'I want some milk.'],
e10:['Unit 10 · At the zoo',[['monkey','con khỉ'],['tiger','con hổ'],['zoo','sở thú'],['animal','động vật']],'I can see a monkey.'],
e11:['Unit 11 · In the playground',[['ball','quả bóng'],['slide','cầu trượt'],['swing','xích đu'],['playground','sân chơi']],'I like the swing.'],
e12:['Unit 12 · At the café',[['cake','bánh ngọt'],['juice','nước ép'],['drink','đồ uống'],['cafe','quán cà phê']],'I like orange juice.'],
e13:['Unit 13 · In the maths class',[['eleven','mười một'],['twelve','mười hai'],['thirteen','mười ba'],['fourteen','mười bốn']],'Eleven plus one is twelve.'],
e14:['Unit 14 · At home',[['mother','mẹ'],['father','bố'],['brother','anh/em trai'],['sister','chị/em gái']],'This is my mother.'],
e15:['Unit 15 · In the clothes shop',[['shirt','áo sơ mi'],['dress','váy liền'],['skirt','chân váy'],['shoes','giày']],'I like this shirt.'],
e16:['Unit 16 · At the campsite',[['tent','lều'],['camp','cắm trại'],['tree','cây'],['lake','hồ']],'The tent is near the lake.']
};
var DATA6={
e1:['Unit 1 · My New School',[['school','trường học'],['classroom','lớp học'],['subject','môn học'],['homework','bài tập về nhà']],'I go to school every day.'],
e2:['Unit 2 · My House',[['bedroom','phòng ngủ'],['kitchen','nhà bếp'],['living room','phòng khách'],['bathroom','phòng tắm']],'There is a sofa in the living room.'],
e3:['Unit 3 · My Friends',[['kind','tốt bụng'],['helpful','hay giúp đỡ'],['clever','thông minh'],['friendly','thân thiện']],'My best friend is kind and helpful.'],
e4:['Unit 4 · My Neighbourhood',[['supermarket','siêu thị'],['square','quảng trường'],['street','đường phố'],['market','chợ']],'This street is wider than that street.'],
e5:['Unit 5 · Natural Wonders of Viet Nam',[['mountain','núi'],['cave','hang động'],['waterfall','thác nước'],['beach','bãi biển']],'You should bring water.'],
e6:['Unit 6 · Our Tet Holiday',[['lucky money','tiền mừng tuổi'],['fireworks','pháo hoa'],['relatives','họ hàng'],['peach blossoms','hoa đào']],'Children receive lucky money at Tet.'],
e7:['Unit 7 · Television',[['programme','chương trình'],['cartoon','phim hoạt hình'],['channel','kênh'],['viewer','người xem']],'I watch cartoons after school.'],
e8:['Unit 8 · Sports and Games',[['football','bóng đá'],['badminton','cầu lông'],['racket','vợt'],['champion','nhà vô địch']],'I play badminton twice a week.'],
e9:['Unit 9 · Cities of the World',[['capital','thủ đô'],['landmark','địa danh'],['crowded','đông đúc'],['palace','cung điện']],'Ha Noi is the capital of Viet Nam.'],
e10:['Unit 10 · Our Houses in the Future',[['robot','rô-bốt'],['appliance','thiết bị'],['solar','năng lượng mặt trời'],['future','tương lai']],'Robots will help us with housework.'],
e11:['Unit 11 · Our Greener World',[['recycle','tái chế'],['rubbish','rác'],['reusable','có thể tái sử dụng'],['environment','môi trường']],'We should recycle plastic bottles.'],
e12:['Unit 12 · Robots',[['robot','rô-bốt'],['repair','sửa chữa'],['lift','nâng'],['understand','hiểu']],'Robots can lift heavy things.']
};
var D=G===2?DATA2:DATA6;
var MODES=G===2?{
weekly:['Vòng tự luyện',15,12,['choice','fill','order','listen','odd','match'],3],
sprint:['Đua tốc độ',10,5,['choice','odd','fill'],3],
listen:['Nghe siêu tốc',10,7,['listen','listen','choice'],3],
words:['Xếp từ & điền từ',12,10,['order','fill','match','odd'],3],
mock:['Thi thử',20,15,['choice','fill','order','listen','odd','match'],0]
}:{
weekly:['Vòng tự luyện',20,15,['choice','fill','order','listen','odd','match'],3],
sprint:['Đua tốc độ',12,6,['choice','odd','fill'],3],
listen:['Nghe siêu tốc',12,8,['listen','listen','choice'],3],
words:['Xếp từ & điền từ',15,10,['order','fill','match','odd'],3],
mock:['Thi thử',30,20,['choice','fill','order','listen','odd','match'],0]
};
var S=null,items=[],idx=0,selected=null,order=[],checked=false,correct=0,points=0,streak=0,bestStreak=0,hearts=3,deadline=0,timerId=null,qStart=0;
function style(){
var x=document.createElement('style');x.textContent='.ioe-banner{margin:0 0 16px;background:linear-gradient(135deg,#eff6ff,#f5f3ff);border:1px solid #c7d2fe}.ioe-logo{font-size:28px;font-weight:950}.ioe-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:13px}.ioe-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:17px}.ioe-card h3{margin:8px 0}.ioe-meta{font-size:12px;color:var(--muted);line-height:1.55;min-height:52px}.ioe-skills{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 18px}.ioe-skill{padding:7px 10px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:12px;font-weight:800}.ioe-hud{display:flex;gap:8px;flex-wrap:wrap}.ioe-hud span{padding:7px 10px;border-radius:10px;background:#f8fafc;border:1px solid var(--line);font-weight:800}.ioe-choice{display:block;width:100%;border:1.5px solid #d9e0ea;background:white;border-radius:14px;padding:13px;text-align:left;cursor:pointer;margin:8px 0}.ioe-choice.selected{border-color:#2563eb;background:#eff6ff}.ioe-input{width:100%;font-size:20px;padding:13px;border:1.5px solid #d9e0ea;border-radius:14px}.ioe-wordbank,.ioe-order{display:flex;gap:8px;flex-wrap:wrap;min-height:48px;padding:10px;border-radius:14px;background:#f8fafc;border:1px dashed #cbd5e1;margin:10px 0}.ioe-word{border:1px solid #cbd5e1;background:white;border-radius:10px;padding:9px 11px;cursor:pointer;font-weight:800}.ioe-word.used{opacity:.35}.ioe-listen{font-size:18px;padding:13px 17px;border-radius:14px;border:0;background:#111827;color:white}.ioe-feedback{display:none;margin-top:12px;padding:12px;border-radius:12px}.ioe-feedback.show{display:block}.ioe-feedback.good{background:#ecfdf3;color:#166534}.ioe-feedback.bad{background:#fff1f2;color:#991b1b}.ioe-history{width:100%;border-collapse:collapse}.ioe-history th,.ioe-history td{padding:9px;border-bottom:1px solid var(--line);text-align:left;font-size:13px}';document.head.appendChild(x)}
function activeTopics(){
var w=currentWeek();
if(G===2){var p=planFor(w),t=p&&p.eng?p.eng:['e1'],m={f1:['e1','e2'],r1:['e1','e2','e3','e4'],f2:['e5','e6'],r2:['e5','e6','e7','e8'],f3:['e9','e10'],r3:['e9','e10','e11','e12'],f4:['e13','e14'],r4:['e13','e14','e15','e16']},o=[];t.forEach(function(k){o=o.concat(m[k]||[k])});return o.filter(function(k,i){return D[k]&&o.indexOf(k)===i})}
if(w<=2)return['e1'];if(w<=4)return['e2','e3'];if(w<=6)return['e3'];if(w<=8)return['e4'];if(w<=10)return['e5'];if(w<=12)return['e6'];if(w<=18)return['e1','e2','e3','e4','e5','e6'];if(w<=20)return['e7'];if(w<=22)return['e8'];if(w<=24)return['e9'];if(w<=26)return['e10'];if(w<=28)return['e11'];if(w<=30)return['e12'];return['e7','e8','e9','e10','e11','e12']}
function scope(){return activeTopics().map(function(k){return D[k][0]}).join(' • ')}
function allWords(){var a=[];Object.keys(D).forEach(function(k){D[k][1].forEach(function(w){a.push([w[0],w[1],k])})});return a}
function pack(correct,ds,seed){var a=[correct].concat(ds.filter(function(x){return x!==correct}).slice(0,3));while(a.length<4)a.push('—');var s=seed%4,r=a.slice(s).concat(a.slice(0,s));return[r,r.indexOf(correct)]}
function distract(topic,i,vi){var a=allWords().filter(function(x){return x[2]!==topic}),o=[];for(var j=0;j<a.length&&o.length<3;j++){var z=a[(i*5+j*7)%a.length][vi?1:0];if(o.indexOf(z)<0)o.push(z)}return o}
function shuffle(a,seed){a=a.slice();for(var i=a.length-1;i>0;i--){var j=(seed*7+i*3)%(i+1),t=a[i];a[i]=a[j];a[j]=t}return a}
function gen(topic,type,i){var d=D[topic],w=d[1][i%d[1].length],p;
if(type==='choice'){p=pack(w[0],distract(topic,i,0),i+1);return{t:type,q:'Choose the word that belongs to “'+d[0]+'”.',a:p[0],c:p[1],e:'Đáp án: '+w[0]+'.'}}
if(type==='fill')return{t:type,q:'Điền từ tiếng Anh: “'+w[1]+'” = ______',ans:w[0],e:'Đáp án: '+w[0]+'.'};
if(type==='order')return{t:type,q:'Sắp xếp các từ thành câu đúng.',words:shuffle(d[2].split(' '),i+2),ans:d[2],e:'Câu đúng: '+d[2]};
if(type==='listen'){p=pack(w[0],distract(topic,i+2,0),i+2);return{t:type,q:'Bấm loa, nghe và chọn từ đúng.',audio:w[0],a:p[0],c:p[1],e:'Từ nghe được: '+w[0]+'.'}}
if(type==='odd'){var own=[d[1][0][0],d[1][1][0],d[1][2][0]],odd=distract(topic,i+4,0)[0];p=pack(odd,own,i+3);return{t:type,q:'Chọn từ KHÁC nhóm.',a:p[0],c:p[1],e:'Từ khác nhóm: '+odd+'.'}}
p=pack(w[1],distract(topic,i+5,1),i+1);return{t:'match',q:'Nối nghĩa đúng: “'+w[0]+'” nghĩa là gì?',a:p[0],c:p[1],e:w[0]+' = '+w[1]+'.'}}
function build(mode){var m=MODES[mode],ts=activeTopics(),a=[];for(var i=0;i<m[1];i++)a.push(gen(ts[i%ts.length],m[3][i%m[3].length],i));return a}
function addSections(){var eng=document.getElementById('eng');if(!eng)return;var sec=document.createElement('section');sec.id='ioe';sec.className='section';sec.innerHTML='<div class="top"><div><button class="btn soft" onclick="go(\'eng\')">← Tiếng Anh</button><h1 style="margin-top:10px">⚡ Luyện IOE · Tiếng Anh lớp '+G+'</h1><div class="muted">Chọn nhanh • điền từ • xếp từ • nghe – chọn • khác nhóm • nối nghĩa</div></div><span class="tag" id="ioeWeekTag"></span></div><div class="card" style="margin-bottom:15px"><b id="ioeScope"></b></div><div class="ioe-grid" id="ioeModes"></div><div class="card" style="margin-top:16px"><h3>Lịch sử luyện IOE</h3><table class="ioe-history"><tbody id="ioeHist"></tbody></table></div>';eng.parentNode.insertBefore(sec,eng.nextSibling);
var game=document.createElement('section');game.id='ioeGame';game.className='section quiz';game.innerHTML='<div class="top"><div><button class="btn soft" onclick="abortIOE()">← Thoát vòng</button><h1 id="ioeTitle" style="margin-top:10px">Luyện IOE</h1><div class="muted" id="ioeGameScope"></div></div><div class="ioe-hud"><span id="ioeLives"></span><span id="ioeStreak"></span><span id="ioePoints"></span><span class="timer" id="ioeTimer"></span></div></div><div class="card"><div class="row"><div class="muted" id="ioeCount"></div><span class="tag" id="ioeType"></span></div><div class="progress" style="margin-top:9px"><i id="ioeBar"></i></div><div class="qtext" id="ioeQ"></div><div id="ioeArea"></div><div class="ioe-feedback" id="ioeFeedback"></div><div class="row" style="margin-top:15px"><div class="mini">Chuỗi đúng liên tiếp được cộng điểm thưởng.</div><button class="btn primary" id="ioeCheck" onclick="checkIOE()">Kiểm tra</button></div></div>';sec.parentNode.insertBefore(game,sec.nextSibling)}
function addBanner(){var eng=document.getElementById('eng');if(!eng||eng.querySelector('.ioe-banner'))return;var top=eng.querySelector('.top'),b=document.createElement('div');b.className='card ioe-banner';b.innerHTML='<div class="row"><div><div class="ioe-logo">⚡ Luyện IOE</div><div class="muted">Luyện theo dạng thi, bám nội dung đang học.</div></div><button class="btn primary" onclick="go(\'ioe\');renderIOEHome()">Vào luyện IOE</button></div>';top.parentNode.insertBefore(b,top.nextSibling)}
function renderIOEHome(){var e=document.getElementById('ioeWeekTag');if(!e)return;e.textContent='Tuần '+currentWeek();document.getElementById('ioeScope').textContent='Phạm vi: '+scope();var box=document.getElementById('ioeModes');box.innerHTML='';Object.keys(MODES).forEach(function(k){var m=MODES[k],ico={weekly:'🏁',sprint:'⚡',listen:'🔊',words:'🧩',mock:'🏆'}[k],d=document.createElement('div');d.className='ioe-card';d.innerHTML='<div style="font-size:28px">'+ico+'</div><h3>'+m[0]+'</h3><div class="ioe-meta">'+m[1]+' câu • '+m[2]+' phút<br>'+ (k==='mock'?'Thi tổng hợp, không mất mạng.':'Có 3 mạng; trộn dạng bài phù hợp.')+'</div><button class="btn primary">Bắt đầu</button>';d.querySelector('button').onclick=function(){startIOE(k)};box.appendChild(d)});var st=state(),h=st.ioe||[],tb=document.getElementById('ioeHist');tb.innerHTML=h.length?'':'<tr><td class="muted">Chưa có lượt luyện IOE.</td></tr>';h.slice(0,8).forEach(function(r){tb.innerHTML+='<tr><td>'+new Date(r.date).toLocaleDateString('vi-VN')+'</td><td>'+r.label+'</td><td><b>'+r.percent+'%</b></td><td>'+r.points+'⭐</td></tr>'})}
function startIOE(mode){var m=MODES[mode];S={mode:mode,label:m[0],lives:m[4]};items=build(mode);idx=0;selected=null;order=[];checked=false;correct=0;points=0;streak=0;bestStreak=0;hearts=m[4]||999;deadline=Date.now()+m[2]*60000;go('ioeGame');document.getElementById('ioeTitle').textContent='⚡ '+m[0];document.getElementById('ioeGameScope').textContent='Tuần '+currentWeek()+' • '+scope();if(timerId)clearInterval(timerId);timerId=setInterval(tick,1000);tick();renderQ()}
function typeName(t){return{choice:'Chọn nhanh',fill:'Điền từ',order:'Xếp từ',listen:'Nghe – chọn',odd:'Khác nhóm',match:'Nối nghĩa'}[t]}
function norm(s){return String(s||'').toLowerCase().replace(/[.,!?]/g,'').replace(/\s+/g,' ').trim()}
function renderQ(){var q=items[idx];selected=null;order=[];checked=false;qStart=Date.now();document.getElementById('ioeCount').textContent='Câu '+(idx+1)+'/'+items.length;document.getElementById('ioeType').textContent=typeName(q.t);document.getElementById('ioeBar').style.width=(idx/items.length*100)+'%';document.getElementById('ioeQ').textContent=q.q;document.getElementById('ioeFeedback').className='ioe-feedback';document.getElementById('ioeCheck').textContent='Kiểm tra';hud();var a=document.getElementById('ioeArea');a.innerHTML='';
if(['choice','listen','odd','match'].indexOf(q.t)>=0){if(q.t==='listen'){var sp=document.createElement('button');sp.className='ioe-listen';sp.textContent='🔊 Nghe';sp.onclick=function(){speak(q.audio)};a.appendChild(sp)}q.a.forEach(function(x,i){var b=document.createElement('button');b.className='ioe-choice';b.textContent=String.fromCharCode(65+i)+'. '+x;b.onclick=function(){if(checked)return;selected=i;a.querySelectorAll('.ioe-choice').forEach(function(z){z.classList.remove('selected')});b.classList.add('selected')};a.appendChild(b)})}
else if(q.t==='fill'){var inp=document.createElement('input');inp.id='ioeFill';inp.className='ioe-input';inp.placeholder='Gõ đáp án tiếng Anh…';inp.onkeydown=function(e){if(e.key==='Enter')checkIOE()};a.appendChild(inp)}
else{var tar=document.createElement('div');tar.id='ioeOrder';tar.className='ioe-order';tar.textContent='Câu của em sẽ hiện ở đây…';a.appendChild(tar);var bank=document.createElement('div');bank.className='ioe-wordbank';q.words.forEach(function(w){var b=document.createElement('button');b.className='ioe-word';b.textContent=w;b.onclick=function(){if(checked||b.classList.contains('used'))return;b.classList.add('used');order.push(w);document.getElementById('ioeOrder').textContent=order.join(' ')};bank.appendChild(b)});a.appendChild(bank);var r=document.createElement('button');r.className='btn soft';r.textContent='Làm lại câu';r.onclick=function(){order=[];bank.querySelectorAll('.ioe-word').forEach(function(x){x.classList.remove('used')});tar.textContent='Câu của em sẽ hiện ở đây…'};a.appendChild(r)}}
function speak(t){if(!('speechSynthesis'in window)){toast('Thiết bị chưa hỗ trợ phát âm tự động.');return}speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=G===2?.72:.88;speechSynthesis.speak(u)}
function checkIOE(){var q=items[idx],ok=false,b=document.getElementById('ioeCheck');if(checked){idx++;if(idx>=items.length)return finish(false);renderQ();return}if(['choice','listen','odd','match'].indexOf(q.t)>=0){if(selected===null)return toast('Chọn một đáp án trước.');ok=selected===q.c}else if(q.t==='fill'){var v=document.getElementById('ioeFill').value;if(!v.trim())return toast('Gõ đáp án trước.');ok=norm(v)===norm(q.ans)}else{if(!order.length)return toast('Hãy xếp các từ trước.');ok=norm(order.join(' '))===norm(q.ans)}checked=true;var f=document.getElementById('ioeFeedback');if(ok){correct++;var gain=10+Math.min(10,streak*2)+Math.max(0,5-Math.floor((Date.now()-qStart)/4000));streak++;bestStreak=Math.max(bestStreak,streak);points+=gain;f.className='ioe-feedback show good';f.innerHTML='<b>✓ Chính xác! +'+gain+' điểm</b><br>'+q.e}else{streak=0;if(S.lives>0)hearts--;f.className='ioe-feedback show bad';f.innerHTML='<b>✗ Chưa đúng.</b><br>'+q.e}hud();b.textContent=(idx===items.length-1||hearts<=0)?'Xem kết quả':'Câu tiếp theo';if(hearts<=0)setTimeout(function(){finish(false)},600)}
function hud(){document.getElementById('ioeLives').textContent=S&&S.lives>0?('❤️'.repeat(Math.max(0,hearts))+'🤍'.repeat(Math.max(0,S.lives-hearts))):'🏆 Thi thử';document.getElementById('ioeStreak').textContent='🔥 '+streak;document.getElementById('ioePoints').textContent='⭐ '+points}
function tick(){var ms=Math.max(0,deadline-Date.now()),m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),e=document.getElementById('ioeTimer');if(e)e.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(ms<=0&&S)finish(true)}
function finish(time){if(!S)return;if(timerId){clearInterval(timerId);timerId=null}var pct=Math.round(correct/items.length*100),st=state();st.ioe=st.ioe||[];st.ioe.unshift({date:new Date().toISOString(),label:S.label,percent:pct,correct:correct,total:items.length,points:points,bestStreak:bestStreak});st.ioe=st.ioe.slice(0,30);st.xp=(st.xp||0)+correct*5;localStorage.setItem(key(),JSON.stringify(st));var msg=(time?'Hết giờ. ':'')+'Kết quả '+pct+'% • '+correct+'/'+items.length+' câu đúng.';S=null;items=[];go('ioe');renderIOEHome();toast(msg)}
window.abortIOE=function(){if(!S)return go('ioe');if(confirm('Thoát vòng luyện? Kết quả hiện tại sẽ không được lưu.')){if(timerId)clearInterval(timerId);timerId=null;S=null;go('ioe');renderIOEHome()}};
window.startIOE=startIOE;window.checkIOE=checkIOE;window.renderIOEHome=renderIOEHome;
style();addSections();var old=window.renderSubject;window.renderSubject=function(s){old(s);if(s==='eng')addBanner()};addBanner();var oldGo=window.go;window.go=function(id){oldGo(id);if(id==='ioe')renderIOEHome()};renderIOEHome();
})();